### Test
GET http://localhost:3000


### Register
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "abcdef",
  "name": "John"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "abcdef"
}
